### PR TITLE
Removed dependency on discovery

### PR DESCRIPTION
**Pull request by Nyholm**
Removed discovery by forcing the user to provide with a HttpClient and HttpFactory. This will make the installation process easier. 

This will fix issue #22 and maybe address issue #21.

### CODE REVIEW

**Comment by onlime** [comment]
Can't get it running since your latest commit 4edfa4dd3aa594cabf47b1b8333c1703dec282d4.

I am getting a **"Puli Factory is not available"** RuntimeException in php-http/discovery/src/ClassDiscovery.php at line 32, ClassDiscovery::getPuliFactory()
This error only occurs once I click on the "Send selected translations to SaaS" in Symfony 3.0.2 profiler.

My setup:

```bash
$ composer require php-http/guzzle6-adapter
$ composer require php-http/httplug-bundle
$ composer require happyr/translation-bundle:dev-master@dev
```
```php
# AppKernel.php
<?php
public function registerBundles()
{
	// ...
	if (in_array($this->getEnvironment(), ['dev', 'test'], true)) {
                // ...
		$bundles[] = new Http\HttplugBundle\HttplugBundle();
		$bundles[] = new Happyr\TranslationBundle\HappyrTranslationBundle();
	}
}
```

```yaml
# app/config/config_dev.yml

happyr_translation:
  locales: ['de_CH','en']
  domains: ['messages','validators']
  projects:
    onlime:
      api_key: %loco_apikey_rw%
```
```yaml
# app/config/routing_dev.yml

_happyr_translation:
  resource: '@HappyrTranslationBundle/Resources/config/routing_dev.yml'
```

php-http/httplug-bundle requires php-http/discovery, which seems to complain about missing Puli (undefined `PULI_FACTORY_CLASS` constant). I am not using Puli anywhere yet.

**Comment by DamienHarper** [comment]
@onlime You can fully get rid of Puli by setting this in your config.yml (setting classes disables discovery which in turn involves Puli -- https://github.com/php-http/HttplugBundle)

```yaml
httplug:
    clients:
        guzzle6:
            factory: 'httplug.factory.guzzle6'
    main_alias:
        client: 'httplug.client.guzzle6'
    classes:
        # uses discovery if not specified
        client: Http\Adapter\Guzzle6\Client
        message_factory: Http\Message\MessageFactory\GuzzleMessageFactory
        uri_factory: Http\Message\UriFactory\GuzzleUriFactory
        stream_factory: Http\Message\StreamFactory\GuzzleStreamFactory

```

**Comment by onlime** [comment]
Thanks a lot, this works great!
Could you possible include this as a recommended configuration setup in your README.md Install/Configure section? I found it kind of hard to get to this information, especially since HttplugBundle does not give us an example of how to setup httplug without using discovery.

Your bundle is so great it should be accessible to everybody!

**Comment by Nyholm** [comment]
Interesting. I'll send a PR to HttplugBundle. It should be explained there.

**Comment by onlime** [comment]
Thanks for this PR. Sounds reasonable to document it there.

**Comment by TomasVotruba** [comment]
Awesome, thanks @Nyholm

**Pull request merged**
