### PR TITLE
fixes for loco translation service

### PR DESCRIPTION
**Pull request by onlime**
fixed some typos in translation service
updated documentation

### CODE REVIEW

**Comment by mastercoding** [comment]
Just commented another pull request, but this one is more feature complete. Could you merge this @Nyholm

**Comment by Nyholm** [comment]
I will have a look this afternoon.

**Comment by onlime** [comment]
@Nyholm Thx! We greatly appreciate. Your bundle is the real thing! Switched from JMSTranslationBundle to HappyrTranslationBundle & Loco - a wonderful combination. Your [blog article](http://developer.happyr.com/how-happyr-work-with-symfony-translations) opened my eyes. Even managed to upgrade my project from Symfony 2.8 to 3.0 yesterday, so your bundle is already partly tested on Symfony3 and works great so far with my applied fixes.

Thank you very much!

**Comment by jarro** [comment]
Agreed delete,  https://github.com/Happyr/TranslationBundle/pull/15   This covers the same issue and is more complete.

**Comment by Nyholm** [comment]
Thank you for providing this fix. Really appreciated.

**Pull request merged**
